"""initial schema

Revision ID: 0c9daae2ce72
Revises:
Create Date: 2026-07-27 18:44:23.915019
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0c9daae2ce72"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables carrying a NOT NULL tenant_id. Row-level security on each is the
# database backstop behind the tenant-scoped repository layer: when the
# application connects under a non-owner role, a query without the
# transaction-local app.tenant_id GUC returns zero rows.
TENANT_OWNED_TABLES = (
    "tenant_members",
    "tenant_config",
    "services",
    "price_rules",
    "business_hours",
    "holiday_overrides",
    "phone_numbers",
    "calls",
    "turns",
    "tool_executions",
    "bookings",
    "messages",
    "escalations",
    "guardrail_events",
    "calendar_connections",
    "usage_records",
)

# Native enum types created with the tables; drop_table does not remove
# them, so downgrade must (in reverse dependency order it's irrelevant —
# they have no interdependencies).
ENUM_TYPES = (
    "tenant_status",
    "member_role",
    "member_status",
    "call_direction",
    "call_outcome",
    "urgency",
    "recording_status",
    "transcript_status",
    "processing_status",
    "turn_role",
    "tool_execution_status",
    "booking_status",
    "reconciliation_status",
    "delivery_status",
    "escalation_reason",
    "escalation_status",
    "guardrail_type",
    "guardrail_action",
    "calendar_connection_status",
    "provider_event_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("payload_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("received", "processed", "failed", "ignored", name="provider_event_status"),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_events")),
        sa.UniqueConstraint("provider", "external_event_id", name="uq_provider_event"),
    )
    op.create_index("ix_provider_events_status", "provider_events", ["status"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("vertical", sa.String(length=40), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "onboarding",
                "testing",
                "active",
                "paused",
                "suspended",
                "churned",
                name="tenant_status",
            ),
            nullable=False,
        ),
        sa.Column("plan_label", sa.String(length=80), nullable=True),
        sa.Column("external_auth_org_id", sa.String(length=120), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,78}$'", name=op.f("ck_tenants_slug_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("external_auth_org_id", name=op.f("uq_tenants_external_auth_org_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("actor_external_user_id", sa.String(length=120), nullable=True),
        sa.Column("actor_role", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.String(length=120), nullable=True),
        sa.Column("before_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_logs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_tenant_created", "audit_logs", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "business_hours",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closed OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)",
            name=op.f("ck_business_hours_open_hours_valid"),
        ),
        sa.CheckConstraint(
            "weekday >= 0 AND weekday <= 6", name=op.f("ck_business_hours_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_business_hours_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_hours")),
        sa.UniqueConstraint("tenant_id", "weekday", name="uq_hours_tenant_weekday"),
    )
    op.create_index("ix_business_hours_tenant_id", "business_hours", ["tenant_id"], unique=False)
    op.create_table(
        "calendar_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_calendar_id", sa.String(length=200), nullable=True),
        sa.Column("encrypted_access_token", sa.Text(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("connected", "expired", "revoked", "error", name="calendar_connection_status"),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_calendar_connections_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_connections")),
        sa.UniqueConstraint("tenant_id", "provider", name="uq_calendar_tenant_provider"),
    )
    op.create_index(
        "ix_calendar_connections_tenant_id", "calendar_connections", ["tenant_id"], unique=False
    )
    op.create_table(
        "holiday_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "closed OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)",
            name=op.f("ck_holiday_overrides_override_hours_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_holiday_overrides_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holiday_overrides")),
        sa.UniqueConstraint("tenant_id", "date", name="uq_holiday_tenant_date"),
    )
    op.create_index(
        "ix_holiday_overrides_tenant_id", "holiday_overrides", ["tenant_id"], unique=False
    )
    op.create_table(
        "phone_numbers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("e164", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_sid", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("voice_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "e164 ~ '^\\+[1-9][0-9]{6,14}$'", name=op.f("ck_phone_numbers_e164_format")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_phone_numbers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_numbers")),
        sa.UniqueConstraint("e164", name=op.f("uq_phone_numbers_e164")),
    )
    op.create_index("ix_phone_numbers_tenant_id", "phone_numbers", ["tenant_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("name_normalized", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_minutes > 0 AND duration_minutes <= 480",
            name=op.f("ck_services_duration_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_services_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("tenant_id", "name_normalized", name="uq_service_tenant_name"),
    )
    op.create_index("ix_services_tenant_id", "services", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_config",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("greeting", sa.Text(), nullable=True),
        sa.Column("persona", sa.Text(), nullable=True),
        sa.Column("voice_id", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("recording_enabled", sa.Boolean(), nullable=False),
        sa.Column("recording_consent_text", sa.Text(), nullable=True),
        sa.Column("escalation_number", sa.String(length=20), nullable=True),
        sa.Column("max_call_seconds", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("service_area", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("escalation_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("configuration_version", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "escalation_number IS NULL OR escalation_number ~ '^\\+[1-9][0-9]{6,14}$'",
            name=op.f("ck_tenant_config_escalation_number_e164"),
        ),
        sa.CheckConstraint(
            "max_call_seconds > 0 AND max_call_seconds <= 3600",
            name=op.f("ck_tenant_config_max_call_seconds_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_config_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenant_config")),
    )
    op.create_table(
        "tenant_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("external_user_id", sa.String(length=120), nullable=False),
        sa.Column(
            "role", sa.Enum("client_owner", "client_staff", name="member_role"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("invited", "active", "disabled", name="member_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_members_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_members")),
        sa.UniqueConstraint("tenant_id", "external_user_id", name="uq_member_tenant_user"),
    )
    op.create_index("ix_tenant_members_tenant_id", "tenant_members", ["tenant_id"], unique=False)
    op.create_table(
        "calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("phone_number_id", sa.UUID(), nullable=True),
        sa.Column("provider_call_sid", sa.String(length=64), nullable=False),
        sa.Column("from_number_encrypted", sa.Text(), nullable=True),
        sa.Column("from_number_hash", sa.String(length=64), nullable=True),
        sa.Column("from_number_last_four", sa.String(length=4), nullable=True),
        sa.Column("to_number", sa.String(length=20), nullable=False),
        sa.Column(
            "direction", sa.Enum("inbound", "outbound", name="call_direction"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "booked",
                "message_taken",
                "transferred",
                "answered_inquiry",
                "caller_hangup",
                "failed",
                name="call_outcome",
            ),
            nullable=True,
        ),
        sa.Column(
            "urgency", sa.Enum("emergency", "urgent", "routine", name="urgency"), nullable=True
        ),
        sa.Column(
            "recording_status",
            sa.Enum(
                "disabled",
                "in_progress",
                "pending_fetch",
                "stored",
                "deleted",
                "failed",
                name="recording_status",
            ),
            nullable=False,
        ),
        sa.Column("recording_object_key", sa.String(length=300), nullable=True),
        sa.Column(
            "transcript_status",
            sa.Enum("pending", "partial", "complete", "failed", name="transcript_status"),
            nullable=False,
        ),
        sa.Column(
            "post_processing_status",
            sa.Enum("pending", "in_progress", "complete", "failed", name="processing_status"),
            nullable=False,
        ),
        sa.Column("estimated_cost_cents", sa.BigInteger(), nullable=True),
        sa.Column("failure_category", sa.String(length=80), nullable=True),
        sa.Column("failure_detail_safe", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name=op.f("ck_calls_duration_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["phone_number_id"],
            ["phone_numbers.id"],
            name=op.f("fk_calls_phone_number_id_phone_numbers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_calls_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("provider_call_sid", name=op.f("uq_calls_provider_call_sid")),
    )
    op.create_index("ix_calls_from_hash", "calls", ["tenant_id", "from_number_hash"], unique=False)
    op.create_index("ix_calls_post_processing", "calls", ["post_processing_status"], unique=False)
    op.create_index("ix_calls_tenant_outcome", "calls", ["tenant_id", "outcome"], unique=False)
    op.create_index("ix_calls_tenant_started", "calls", ["tenant_id", "started_at"], unique=False)
    op.create_table(
        "price_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("minimum_amount_cents", sa.BigInteger(), nullable=True),
        sa.Column("maximum_amount_cents", sa.BigInteger(), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("customer_visible", sa.Boolean(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(minimum_amount_cents IS NULL OR minimum_amount_cents >= 0) AND "
            "(maximum_amount_cents IS NULL OR maximum_amount_cents >= 0)",
            name=op.f("ck_price_rules_amounts_non_negative"),
        ),
        sa.CheckConstraint(
            "minimum_amount_cents IS NULL OR maximum_amount_cents IS NULL "
            "OR minimum_amount_cents <= maximum_amount_cents",
            name=op.f("ck_price_rules_min_lte_max"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_price_rules_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_price_rules_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_rules")),
    )
    op.create_index("ix_price_rules_service_id", "price_rules", ["service_id"], unique=False)
    op.create_index("ix_price_rules_tenant_id", "price_rules", ["tenant_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_phone_encrypted", sa.Text(), nullable=True),
        sa.Column("customer_phone_hash", sa.String(length=64), nullable=True),
        sa.Column("customer_phone_last_four", sa.String(length=4), nullable=True),
        sa.Column("address_encrypted", sa.Text(), nullable=True),
        sa.Column("notes_encrypted", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("external_calendar_event_id", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "failed",
                "cancelled",
                "reconciliation_required",
                name="booking_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "reconciliation_status",
            sa.Enum("not_required", "pending", "resolved", name="reconciliation_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_bookings_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_bookings_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_bookings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_bookings_idempotency_key")),
    )
    op.create_index(
        "ix_bookings_tenant_scheduled", "bookings", ["tenant_id", "scheduled_at"], unique=False
    )
    op.create_index("ix_bookings_tenant_status", "bookings", ["tenant_id", "status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_phone_encrypted", sa.Text(), nullable=True),
        sa.Column("customer_phone_last_four", sa.String(length=4), nullable=True),
        sa.Column("body_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "urgency", sa.Enum("emergency", "urgent", "routine", name="urgency"), nullable=False
        ),
        sa.Column(
            "delivery_status",
            sa.Enum("pending", "sent", "failed", name="delivery_status"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_messages_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_messages_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_tenant_created", "messages", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_messages_tenant_urgency", "messages", ["tenant_id", "urgency"], unique=False
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("caller", "assistant", "system", name="turn_role"), nullable=False
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("endpointing_ms", sa.Integer(), nullable=True),
        sa.Column("stt_finalization_ms", sa.Integer(), nullable=True),
        sa.Column("llm_ttft_ms", sa.Integer(), nullable=True),
        sa.Column("tts_ttfb_ms", sa.Integer(), nullable=True),
        sa.Column("first_playback_ms", sa.Integer(), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("barge_in", sa.Boolean(), nullable=False),
        sa.Column("interrupted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("turn_index >= 0", name=op.f("ck_turns_turn_index_non_negative")),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_turns_call_id_calls"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_turns_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("call_id", "turn_index", name="uq_turn_call_index"),
    )
    op.create_index("ix_turns_call_id", "turns", ["call_id"], unique=False)
    op.create_index("ix_turns_tenant_id", "turns", ["tenant_id"], unique=False)
    op.create_table(
        "usage_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("usage_type", sa.String(length=60), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("cost_cents", sa.BigInteger(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_usage_records_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_usage_records_call_id_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_usage_records_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        "ix_usage_records_tenant_recorded",
        "usage_records",
        ["tenant_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "escalations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "emergency",
                "human_request",
                "intent_failure",
                "system_error",
                name="escalation_reason",
            ),
            nullable=False,
        ),
        sa.Column("destination_last_four", sa.String(length=4), nullable=True),
        sa.Column("initiated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "initiated", "connected", "failed", "fell_back_to_message", name="escalation_status"
            ),
            nullable=False,
        ),
        sa.Column("fallback_message_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_escalations_call_id_calls"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["fallback_message_id"],
            ["messages.id"],
            name=op.f("fk_escalations_fallback_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_escalations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalations")),
    )
    op.create_index("ix_escalations_call_id", "escalations", ["call_id"], unique=False)
    op.create_index("ix_escalations_tenant_id", "escalations", ["tenant_id"], unique=False)
    op.create_table(
        "guardrail_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=True),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column(
            "guardrail_type",
            sa.Enum(
                "price_invention",
                "service_invention",
                "availability_invention",
                "off_scope",
                "prompt_injection",
                "sensitive_content",
                name="guardrail_type",
            ),
            nullable=False,
        ),
        sa.Column("input_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "action",
            sa.Enum("blocked", "rewritten", "escalated", "logged", name="guardrail_action"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_guardrail_events_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_guardrail_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name=op.f("fk_guardrail_events_turn_id_turns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardrail_events")),
    )
    op.create_index(
        "ix_guardrail_events_tenant_created",
        "guardrail_events",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("input_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("success", "error", "timeout", "rejected", name="tool_execution_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_category", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_tool_executions_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tool_executions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name=op.f("fk_tool_executions_turn_id_turns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
    )
    op.create_index("ix_tool_executions_call_id", "tool_executions", ["call_id"], unique=False)
    op.create_index("ix_tool_executions_tenant_id", "tool_executions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # --- Row-level security (tenant isolation backstop) ---
    for table in TENANT_OWNED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
            WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_executions_tenant_id", table_name="tool_executions")
    op.drop_index("ix_tool_executions_call_id", table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index("ix_guardrail_events_tenant_created", table_name="guardrail_events")
    op.drop_table("guardrail_events")
    op.drop_index("ix_escalations_tenant_id", table_name="escalations")
    op.drop_index("ix_escalations_call_id", table_name="escalations")
    op.drop_table("escalations")
    op.drop_index("ix_usage_records_tenant_recorded", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index("ix_turns_tenant_id", table_name="turns")
    op.drop_index("ix_turns_call_id", table_name="turns")
    op.drop_table("turns")
    op.drop_index("ix_messages_tenant_urgency", table_name="messages")
    op.drop_index("ix_messages_tenant_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_bookings_tenant_status", table_name="bookings")
    op.drop_index("ix_bookings_tenant_scheduled", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_price_rules_tenant_id", table_name="price_rules")
    op.drop_index("ix_price_rules_service_id", table_name="price_rules")
    op.drop_table("price_rules")
    op.drop_index("ix_calls_tenant_started", table_name="calls")
    op.drop_index("ix_calls_tenant_outcome", table_name="calls")
    op.drop_index("ix_calls_post_processing", table_name="calls")
    op.drop_index("ix_calls_from_hash", table_name="calls")
    op.drop_table("calls")
    op.drop_index("ix_tenant_members_tenant_id", table_name="tenant_members")
    op.drop_table("tenant_members")
    op.drop_table("tenant_config")
    op.drop_index("ix_services_tenant_id", table_name="services")
    op.drop_table("services")
    op.drop_index("ix_phone_numbers_tenant_id", table_name="phone_numbers")
    op.drop_table("phone_numbers")
    op.drop_index("ix_holiday_overrides_tenant_id", table_name="holiday_overrides")
    op.drop_table("holiday_overrides")
    op.drop_index("ix_calendar_connections_tenant_id", table_name="calendar_connections")
    op.drop_table("calendar_connections")
    op.drop_index("ix_business_hours_tenant_id", table_name="business_hours")
    op.drop_table("business_hours")
    op.drop_index("ix_audit_logs_tenant_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("tenants")
    op.drop_index("ix_provider_events_status", table_name="provider_events")
    op.drop_table("provider_events")
    # ### end Alembic commands ###

    # Native enum types are not dropped by drop_table.
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
