"""simulator sessions and call transport

Revision ID: 2b546cedf212
Revises: 9aefcb09fb40
Create Date: 2026-07-27 19:56:16.818748
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2b546cedf212"
down_revision: str | None = "9aefcb09fb40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulator_sessions",
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("failure_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_simulator_sessions_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_simulator_sessions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("call_id", name=op.f("pk_simulator_sessions")),
    )
    op.create_index(
        "ix_simulator_sessions_tenant_id", "simulator_sessions", ["tenant_id"], unique=False
    )
    # add_column does not auto-create enum types (create_table does).
    sa.Enum("phone", "browser_text", name="call_transport").create(op.get_bind(), checkfirst=True)
    # server_default backfills existing rows as phone calls.
    op.add_column(
        "calls",
        sa.Column(
            "transport",
            sa.Enum("phone", "browser_text", name="call_transport"),
            nullable=False,
            server_default="phone",
        ),
    )
    # ### end Alembic commands ###

    # Row-level security for the new tenant-owned table.
    op.execute("ALTER TABLE simulator_sessions ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON simulator_sessions
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "transport")
    op.drop_index("ix_simulator_sessions_tenant_id", table_name="simulator_sessions")
    op.drop_table("simulator_sessions")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS call_transport")
