"""recording retention and legal hold

Revision ID: 905b6bd15493
Revises: c1f2a9d0e4b7
Create Date: 2026-07-27 22:58:03.229251
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "905b6bd15493"
down_revision: str | None = "c1f2a9d0e4b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column("recording_legal_hold", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "tenant_config", sa.Column("recording_retention_days", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_config", "recording_retention_days")
    op.drop_column("calls", "recording_legal_hold")
    # ### end Alembic commands ###
