"""config versions and extended settings

Revision ID: 9aefcb09fb40
Revises: a82561ce04d0
Create Date: 2026-07-27 19:34:31.464673
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9aefcb09fb40"
down_revision: str | None = "a82561ce04d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft",
                "pending_review",
                "active",
                "superseded",
                "rejected",
                name="config_version_state",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_config_versions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config_versions")),
        sa.UniqueConstraint("tenant_id", "version", name="uq_config_version_tenant_version"),
    )
    op.create_index("ix_config_versions_tenant_id", "config_versions", ["tenant_id"], unique=False)
    op.create_index(
        "uq_config_versions_one_active",
        "config_versions",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_index(
        "uq_config_versions_one_open",
        "config_versions",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('draft', 'pending_review')"),
    )
    op.add_column("tenant_config", sa.Column("address", sa.Text(), nullable=True))
    op.add_column("tenant_config", sa.Column("website", sa.String(length=200), nullable=True))
    op.add_column("tenant_config", sa.Column("after_hours_greeting", sa.Text(), nullable=True))
    op.add_column("tenant_config", sa.Column("speaking_style", sa.String(length=80), nullable=True))
    op.add_column(
        "tenant_config",
        sa.Column("filler_phrases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    # Row-level security for the new tenant-owned table.
    op.execute("ALTER TABLE config_versions ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON config_versions
        USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
        WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_config", "filler_phrases")
    op.drop_column("tenant_config", "speaking_style")
    op.drop_column("tenant_config", "after_hours_greeting")
    op.drop_column("tenant_config", "website")
    op.drop_column("tenant_config", "address")
    op.drop_index(
        "uq_config_versions_one_open",
        table_name="config_versions",
        postgresql_where=sa.text("state IN ('draft', 'pending_review')"),
    )
    op.drop_index(
        "uq_config_versions_one_active",
        table_name="config_versions",
        postgresql_where=sa.text("state = 'active'"),
    )
    op.drop_index("ix_config_versions_tenant_id", table_name="config_versions")
    op.drop_table("config_versions")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS config_version_state")
