"""tenant onboarding fields

Revision ID: a82561ce04d0
Revises: 0c9daae2ce72
Create Date: 2026-07-27 19:06:11.060902
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a82561ce04d0"
down_revision: str | None = "0c9daae2ce72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant_config", sa.Column("business_phone", sa.String(length=20), nullable=True))
    op.add_column(
        "tenant_config",
        sa.Column("activation_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # server_default backfills existing rows; the application default takes
    # over for new inserts.
    op.add_column(
        "tenants", sa.Column("country", sa.String(length=2), nullable=False, server_default="US")
    )
    op.add_column("tenants", sa.Column("expected_monthly_calls", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "expected_monthly_calls")
    op.drop_column("tenants", "country")
    op.drop_column("tenant_config", "activation_state")
    op.drop_column("tenant_config", "business_phone")
    # ### end Alembic commands ###
